version: '3'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    networks:
      - nodenet
    ports:
      - "8080:80"
    tty: true
    depends_on:
      - app

  app:
    build: ./node
    container_name: app
    #entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    tty: true
    volumes:
      - ./node:/usr/src/app
    networks:
      - nodenet
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=groot
      - MYSQL_USER_PASSWORD=groot
      - MYSQL_ROOT_PASSWORD=groot
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge